In [16]:
#Importing Libraries
import numpy as np
import pandas as pd


In [17]:
A = [1, 2, 3, 4, 5, 6]
B = [13, 21, 34]
A.extend(B)
A_B=A
print(A_B)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


In [18]:

print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#Load dataset
fuel_data=pd.read_csv('fuel_data.csv')
#Get a view of the head
fuel_data.head()

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

In [20]:
#lowest average fuel cost per unit burned
fuel_data.groupby('fuel_type_code_pudl').fuel_cost_per_unit_burned.mean().sort_values()

fuel_type_code_pudl
gas          13.659397
other        18.253856
waste        19.518122
coal         67.421830
oil         168.877086
nuclear    4955.157002
Name: fuel_cost_per_unit_burned, dtype: float64

In [21]:
#### standard deviation and 75th percentile of the measure of energy per unit(fuel_mmbtu_per_unit) in two decimal places
print("The standard deviation is:", round(fuel_data['fuel_mmbtu_per_unit'].std(), 2),
     "\nThe 75th percentile is:", round(fuel_data['fuel_mmbtu_per_unit'].quantile(0.75), 2))

The standard deviation is: 10.6 
The 75th percentile is: 17.01


In [22]:
#skewness and kurtosis for the fuel quantity burned in two decimal places
print("Skewness:", round(fuel_data.fuel_qty_burned.skew(), 2),
      "\nKurtosis:", round(fuel_data.fuel_qty_burned.kurt(), 2))

Skewness: 15.85 
Kurtosis: 651.37


In [23]:
#Getting features with missing values
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [24]:
#percentage of missing rows
Total_rows = len(fuel_data)
Total_missing_rows = fuel_data['fuel_unit'].isnull().sum()
print("Percentage of missing rows: ", round((Total_missing_rows/Total_rows)*100, 3))

Percentage of missing rows:  0.61


In [25]:
#Category of feature with missing values
fuel_data['fuel_unit'].dtype

dtype('O')

In [26]:
# second and third lowest correlation with the Fuel Cost Per Unit Burned
fuel_data.corr()['fuel_cost_per_unit_burned'].sort_values()[1:3]

fuel_qty_burned       -0.018535
fuel_mmbtu_per_unit   -0.010034
Name: fuel_cost_per_unit_burned, dtype: float64

In [27]:
#percentage change in the fuel cost per unit burned in 1998 compared to 1994


#fuel cost per unit burned in 1994 for coal
coal_fuel_cost_1994 = fuel_data.loc[(fuel_data['fuel_type_code_pudl'] == 'coal') & ((fuel_data['report_year'] == 1994))]['fuel_cost_per_unit_burned'].sum()
#fuel cost per unit burned in 1998 for coal
coal_fuel_cost_1998 = fuel_data.loc[(fuel_data['fuel_type_code_pudl'] == 'coal') & ((fuel_data['report_year'] == 1998))]['fuel_cost_per_unit_burned'].sum()

##percentage change in the fuel cost per unit burned in 1998 compared to 1994, for coal
percent_change = ((coal_fuel_cost_1998 - coal_fuel_cost_1994) / coal_fuel_cost_1994) * 100
print("Percentage change: {}%".format(round(percent_change)))

Percentage change: -21.0%


In [28]:
#year with the highest average fuel cost per unit delivered
fuel_data.groupby('report_year').fuel_cost_per_unit_delivered.mean().sort_values()[-1:]

report_year
1997    11140.197239
Name: fuel_cost_per_unit_delivered, dtype: float64